In [3]:
import pandas as pd

In [ ]:
from sqlalchemy import create_engine

In [4]:
user ='postgres'
password = '123'
host = '10.0.222.18'
port = '5432'
database = 'tallerdb'

In [5]:
engine=create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}")

In [6]:
sql = 'select * from familia'
familias = pd.read_sql(sql, engine)
print(familias)

sql = 'select * from categoria'
categorias = pd.read_sql(sql, engine)
print(categorias)

   idfamilia   nombre          descripcion
0          1  Bebidas   Todo sobre bebidas
1          2  Lácteos   Todo sobre lácteos
2          3  Escolar  Productos escolares
   idcategoria        nombre  idfamilia
0            1       Gaseosa          1
1            2  Agua Mineral          1
2            3         Leche          2
3            4         Queso          2

In [ ]:
vista_cat = categorias.merge(familias, how='inner' , on='idfamilia')
vista_cat

categoria  Agua Mineral  Gaseosa  Leche  Queso
familia
Bebidas               1        1      0      0
Lácteos               0        0      1      1

In [9]:
vista_cat = categorias.merge (familias, how= 'outer', on='idfamilia')
vista_cat = vista_cat.rename (columns={'nombre_x': 'categoria', 'nombre_y': 'familia'}) 
vista_cat

   idcategoria     categoria  idfamilia  familia          descripcion
0          1.0       Gaseosa          1  Bebidas   Todo sobre bebidas
1          2.0  Agua Mineral          1  Bebidas   Todo sobre bebidas
2          3.0         Leche          2  Lácteos   Todo sobre lácteos
3          4.0         Queso          2  Lácteos   Todo sobre lácteos
4          NaN           NaN          3  Escolar  Productos escolares

In [10]:
vista_cat_resumen = vista_cat[['categoria', 'familia']]
vista_cat_resumen

      categoria  familia
0       Gaseosa  Bebidas
1  Agua Mineral  Bebidas
2         Leche  Lácteos
3         Queso  Lácteos
4           NaN  Escolar

In [11]:
vista_cat_resumen.groupby('familia')['categoria'].count()

familia
Bebidas    2
Escolar    0
Lácteos    2
Name: categoria, dtype: int64

In [12]:
vista_cat_resumen.pivot_table(index='familia', columns='categoria', aggfunc='size', fill_value = 0)

categoria  Agua Mineral  Gaseosa  Leche  Queso
familia
Bebidas               1        1      0      0
Lácteos               0        0      1      1